# This is a basic workflow to help you get started with Actions
name: Terraform Plan & Apply

# Controls when the workflow will run
on:
  # manual run workflow
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
permissions:
  id-token: write
  contents: read

jobs:
  Apply:
    runs-on: ubuntu-latest

    steps:
    # Check current repo using Node.24 runtime
    - uses: actions/checkout@v6

    # Download Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Debug OIDC token claims
      run: |
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -R 'split(".") | .[1] | @base64d | fromjson'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6.2.4
      with:
         role-to-assume: arn:aws:iam::536984667329:role/GitHub-Actions-TFArchitecture
         aws-region: us-east-1
         audience: sts.amazonaws.com

    - name: Initialize Terraform
      run: terraform init
      
    - name: Apply Terraform
      run: terraform apply -auto-approve
        
