# This is a basic workflow to help you get started with Actions
name: Terraform Plan & Apply

# Controls when the workflow will run
on:
  # manual run workflow
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check current repo using Node.24 runtime
    - uses: actions/checkout@v6

    # Download Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v4
     with:
       role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
       aws-region: us-east-1

    run: terraform init

    run: terraform apply -auto-approve
        
